### List All Reports
GET http://localhost:3000/reports
Accept: application/json

###

### List Unprocessed Reports
GET http://localhost:3000/reports/getUnprocessedReports
Accept: application/json

###
### Get Amount Unprocessed Reports
GET http://localhost:3000/reports/countUnprocessedReports
Accept: application/json

###

### Create a Report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "title": "Voorbeeld Probleem",
  "description": "Beschrijving van het probleem in het Nederlands"
}

###

### Process Reports
POST http://localhost:3000/reports/process

###

### List Unresolved Clusters
GET http://localhost:3000/clusters/unresolved
Accept: application/json

###

### Resolve a Cluster
POST http://localhost:3000/clusters/1/resolve
Content-Type: application/json
